### ISSUE TITLE
Drop-down issue in 10.2

### ISSUE THREAD

**Issue by Lotan21** [Lombra/Critline#2]
Getting issue when clicking the drop-down buttons to reset a spell.

Error occured in: Global
Count: 1
Message: Interface/SharedXML/UIDropDownMenu.lua line 91:
   calling 'GetWindow' on bad self (Usage: local window = self:GetWindow())
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: GetWindow()
   [string "@Interface/SharedXML/UIDropDownMenu.lua"]:91: UIDropDownMenu_Initialize()
   [string "@Interface/SharedXML/UIDropDownMenu.lua"]:1167:
      Interface/SharedXML/UIDropDownMenu.lua:1024
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ToggleDropDownMenu()
   [string "@Interface/AddOns/Critline/Libs/Libra/Dropdown.lua"]:80: Toggle()
   [string "@Interface/AddOns/Critline/SpellList.lua"]:58:
      Interface/AddOns/Critline/SpellList.lua:53
Locals:
(*temporary) = <function> defined =[C]:-1

**Comment by Digawen** [comment]
The same thing happens to me. Here is my error message.

2x SharedXML/UIDropDownMenu.lua:91: calling 'GetWindow' on bad self (Usage: local window = self:GetWindow())
[string "=[C]"]: in function `GetWindow'
[string "@SharedXML/UIDropDownMenu.lua"]:91: in function `UIDropDownMenu_Initialize'
[string "@SharedXML/UIDropDownMenu.lua"]:1167: in function <SharedXML/UIDropDownMenu.lua:1024>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ToggleDropDownMenu'
[string "@Critline/Libs/Libra/Dropdown.lua"]:80: in function `Toggle'
[string "@Critline/SpellList.lua"]:58: in function <Critline/SpellList.lua:53>

Locals:
(*temporary) = <table> {
 menuList = <table> {
 }
 _displayMode = "MENU"
 initialize = <function> defined @Critline/SpellList.lua:17
 xOffset = 0
 SetHeight = <function> defined @Critline/Libs/Libra/Dropdown.lua:27
 yOffset = 0
}
