### ISSUE TITLE
Error: 309x Critline/Core.lua:607: attempt to call upvalue 'GetSpellLink' (a nil value)

### ISSUE THREAD

**Issue by araquen** [Lombra/Critline#4]
309x Critline/Core.lua:607: attempt to call upvalue 'GetSpellLink' (a nil value)
[string "@Critline/Core.lua"]:607: in function `eventHandler'
[string "@Critline/Libs/Libra/Addon.lua"]:53: in function <Critline/Libs/Libra/Addon.lua:35>

Locals:
self = <table> {
 messages = <table> {
 }
 modules = <table> {
 }
 treeIndex = <table> {
 }
 db = <table> {
 }
 SlashCmdHandlers = <table> {
 }
 filters = <table> {
 }
 trees = <table> {
 }
 callbacks = <table> {
 }
 spellList = Frame {
 }
 config = Frame {
 }
 name = "Critline"
 L = <table> {
 }
 percharDB = <table> {
 }
}
timestamp = 1721853740.195000
eventType = "SPELL_AURA_APPLIED"
hideCaster = false
sourceGUID = "Player-1129-0AEB9ECA"
sourceName = "Atanae"
sourceFlags = 1297
sourceFlags2 = 0
destGUID = "Player-1129-0AEB9ECA"
destName = "Atanae"
destFlags = 1297
destFlags2 = 0
arg12 = 426341
arg13 = "Tindral's Fowl Fantasia"
arg14 = 1
arg15 = "BUFF"
arg16 = nil
arg17 = nil
arg18 = nil
arg19 = nil
arg20 = nil
arg21 = nil
isPet = nil
isPeriodic = nil
periodic = 1
isHeal = true
spellID = 426341
spellName = "Tindral's Fowl Fantasia"
amount = nil
resisted = 0
critical = nil
rawID = 426341
cachedID = nil
(*temporary) = nil
(*temporary) = "Tindral's Fowl Fantasia"
(*temporary) = "attempt to call upvalue 'GetSpellLink' (a nil value)"
COMBATLOG_FILTER_MINE = 17681
healEvents = <table> {
 SPELL_AURA_APPLIED = true
 SPELL_AURA_REFRESH = true
 SPELL_PERIODIC_HEAL = true
 SPELL_HEAL = true
}
combatEvents = <table> {
}
spellIDCache = <table> {
}
GetSpellLink = nil
spellMappings = <table> {
}
COMBATLOG_OBJECT_CONTROL_PLAYER = 256
COMBATLOG_OBJECT_REACTION_FRIENDLY = 16
COMBATLOG_OBJECT_REACTION_HOSTILE = 64
topRecords = <table> {
 dmg = <table> {
 }
 heal = <table> {
 }
 pet = <table> {
 }
}
callbacks = <table> {
 recurse = 0
 events = <table> {
 }
}

**Comment by araquen** [comment]
Maybe similar:

3x Critline/Core.lua:548: attempt to call upvalue 'GetSpellLink' (a nil value)
[string "@Critline/Core.lua"]:548: in function `FixSpells'
[string "@Critline/Core.lua"]:524: in function `LoadPerCharSettings'
[string "@Critline/Core.lua"]:515: in function `?'
[string "@Critline/Libs/Libra/Addon.lua"]:16: in function <Critline/Libs/Libra/Addon.lua:14>
[string "@Critline/Libs/Libra/Addon.lua"]:39: in function <Critline/Libs/Libra/Addon.lua:35>

Locals:
self = <table> {
 messages = <table> {
 }
 modules = <table> {
 }
 treeIndex = <table> {
 }
 db = <table> {
 }
 SlashCmdHandlers = <table> {
 }
 filters = <table> {
 }
 trees = <table> {
 }
 callbacks = <table> {
 }
 spellList = Frame {
 }
 config = Frame {
 }
 name = "Critline"
 L = <table> {
 }
 percharDB = <table> {
 }
}
(for state) = <table> {
 dmg = <table> {
 }
 heal = <table> {
 }
 pet = <table> {
 }
}
(for control) = "dmg"
k = "dmg"
tree = <table> {
 190984 = <table> {
 }
}
(for state) = <table> {
 190984 = <table> {
 }
}
(for control) = 190984
spellID = 190984
spell = <table> {
 1 = <table> {
 }
}
spellMapping = nil
(*temporary) = nil
(*temporary) = 190984
(*temporary) = "attempt to call upvalue 'GetSpellLink' (a nil value)"
spellMappings = <table> {
}
GetSpellLink = nil

**Comment by Lombra** [comment]
Completed in https://github.com/Lombra/Critline/commit/b6b2d3c8983c19d81261f3e4eed2dd50bfe50d1b.
