### ISSUE TITLE
Error: 1x Critline/Libs/Libra/OptionsFrame.lua:128: attempt to index local 'object' (a nil value)

### ISSUE THREAD

**Issue by araquen** [Lombra/Critline#5]
1x Critline/Libs/Libra/OptionsFrame.lua:128: attempt to index local 'object' (a nil value)
[string "@Critline/Libs/Libra/OptionsFrame.lua"]:128: in function <Critline/Libs/Libra/OptionsFrame.lua:122>
[string "@Critline/Libs/Libra/OptionsFrame.lua"]:146: in function <Critline/Libs/Libra/OptionsFrame.lua:139>
[string "@Critline/Libs/Libra/OptionsFrame.lua"]:376: in function `func'
[string "@Blizzard_SharedXML/Mainline/UIDropDownMenu.lua"]:1034: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:93_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:93_OnClick"]:1>

Locals:
control = GenericLibraWidget3 {
 Label = FontString {
 }
 parent = Frame {
 }
 Right = GenericLibraWidget3Right {
 }
 Left = GenericLibraWidget3Left {
 }
 key = "fontFace"
 Button = GenericLibraWidget3Button {
 }
 Middle = GenericLibraWidget3Middle {
 }
 Text = GenericLibraWidget3Text {
 }
 func = "UpdateFont"
 label = FontString {
 }
 Icon = GenericLibraWidget3Icon {
 }
 noResize = 1
}
method = "func"
key = nil
value = "Friz Quadrata TT"
func = "UpdateFont"
object = nil
(*temporary) = Frame {
 title = FontString {
 }
 category = <table> {
 }
 controls = <table> {
 }
 allcontrols = <table> {
 }
 desc = FontString {
 }
}
(*temporary) = "UpdateFont"
(*temporary) = "string"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'object' (a nil value)"

**Comment by Lombra** [comment]
Completed in https://github.com/Lombra/Critline/commit/b6b2d3c8983c19d81261f3e4eed2dd50bfe50d1b.
